src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    private ?User $author = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publication_date = null;

    #[ORM\Column]
    private ?bool $is_published = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\ManyToMany(targetEntity: BlogCategory::class, mappedBy: 'blog')]
    private Collection $blogCategories;

    public function __toString(): string
    {
        return (string) $this->title;
    }
    
    public function __construct()
    {
        $this->blogCategories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeImmutable
    {
        return $this->publication_date;
    }

    public function setPublicationDate(?\DateTimeImmutable $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function isIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(?bool $is_published): static
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    /**
     * @return Collection<int, BlogCategory>
     */
    public function getBlogCategories(): Collection
    {
        return $this->blogCategories;
    }

    public function addBlogCategory(BlogCategory $blogCategory): static
    {
        if (!$this->blogCategories->contains($blogCategory)) {
            $this->blogCategories->add($blogCategory);
            $blogCategory->addBlog($this);
        }

        return $this;
    }

    public function removeBlogCategory(BlogCategory $blogCategory): static
    {
        if ($this->blogCategories->removeElement($blogCategory)) {
            $blogCategory->removeBlog($this);
        }

        return $this;
    }
}

src/Entity/Content.php
<?php

namespace App\Entity;

use App\Repository\ContentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContentRepository::class)]
class Content
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content_text = null;

    public function __toString(): string
    {
        return (string) $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getContentText(): ?string
    {
        return $this->content_text;
    }

    public function setContentText(?string $content_text): static
    {
        $this->content_text = $content_text;

        return $this;
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PageRepository::class)]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $page_content = null;

    #[ORM\Column(nullable: true)]
    private ?bool $content_first = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_service = null;

    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'pages')]
    private Collection $sections;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getPageContent(): ?string
    {
        return $this->page_content;
    }

    public function setPageContent(?string $page_content): static
    {
        $this->page_content = $page_content;

        return $this;
    }

    public function isContentFirst(): ?bool
    {
        return $this->content_first;
    }

    public function setContentFirst(?bool $content_first): static
    {
        $this->content_first = $content_first;

        return $this;
    }

    public function isIsService(): ?bool
    {
        return $this->is_service;
    }

    public function setIsService(?bool $is_service): static
    {
        $this->is_service = $is_service;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
}

src/Entity/SEO.php
<?php

namespace App\Entity;

use App\Repository\SEORepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SEORepository::class)]
class SEO
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_path = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $keywords = null;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): static
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): static
    {
        $this->keywords = $keywords;

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $template_path = null;

    #[ORM\Column(nullable: true)]
    private ?int $priority = null;

    #[ORM\ManyToMany(targetEntity: Page::class, mappedBy: 'sections')]
    private Collection $pages;

    public function __construct()
    {
        $this->pages = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->description;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTemplatePath(): ?string
    {
        return $this->template_path;
    }

    public function setTemplatePath(?string $template_path): static
    {
        $this->template_path = $template_path;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return Collection<int, Page>
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Page $page): static
    {
        if (!$this->pages->contains($page)) {
            $this->pages->add($page);
            $page->addSection($this);
        }

        return $this;
    }

    public function removePage(Page $page): static
    {
        if ($this->pages->removeElement($page)) {
            $page->removeSection($this);
        }

        return $this;
    }
}

templates/sections/about.html.twig
    <!-- About Start -->
    <section class="about-sec pb-90">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="about-i pr-20 wow slideInRight" data-wow-delay="0ms" data-wow-duration="1200ms">
                        <img src="/site/images/about-s.jpg" class="img-fluid" alt="" />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="min-cont-t pt-40 wow slideInLeft" data-wow-delay="0ms" data-wow-duration="1200ms">
                        <h2 class="sub-bg heading">
                            {{ content['about-us-title'].contentText }}
                        </h2>
                        <p class="pl-50">
                            {{ content['about-us-content'].contentText|nl2br }}
                        </p>
                        <a href="{{path('app_page', {'page': 'about-uzima-well-being-hub' })}}" class="theme-btn btn-style-orange ml-50">
                            {{ content['about-us-cta'].contentText }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About End -->

templates/sections/blog_article.html.twig
<!-- Article Start -->
<section class="service-det pt-0 pb-90">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<div class="min-ser">
					<div class="img-s">
						<img src="{{ asset('site/images/blog_images/' ~ blog_post.featuredImage ) }}" alt="" class="img-fluid" />
					</div>
					<div class="ser-con mt-30">
						{{blog_post.content|raw}}
					</div>
					<hr />
					<div class="">
						{% include ('tmp/accordion.html.twig') %}
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="po-s">
					{% include ('tmp/member_invite.html.twig') %}
					<div class="min-service-box">
						<h3 class="heading-l">Categories</h3>
						<div class="list-ser">
							<ul>
							{% for category in blog_post.blogCategories %}
								<li>
									<a href="#">{{ category }}</a>
								</li>
							{% endfor %}									
							</ul>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</section>
<!-- Article End -->

templates/sections/cta.html.twig
    <!-- cta Start -->
    <section class="vide0-bg pt-90 pb-90 mb-90">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="video-p">
                        <h2>{{ content['cta-title'].contentText }}</h2>
                        <p>{{ content['cta-content'].contentText|nl2br }}</p>
                        <p style="margin-top:5px; text-align: center;"><a style="float:none !important;" href="tel:{{ content['phone-number-wa'].contentText }}" class="theme-btn btn-style-orange btn-h-white">{{ content['phone-cta'].contentText }}</a>
                        <a style="margin-top:5px; float:none !important;" href="https://wa.me/{{content['phone-number-wa'].contentText}}" class="theme-btn btn-style-orange btn-h-white">{{ content['whatsapp-cta'].contentText }}</a>
                        <a style="margin-top:5px; float:none !important;" href="{{ path('app_page', {'page': 'contact-uzima-well-being-hub'} ) }}" class="theme-btn btn-style-orange btn-h-white">{{ content['contact-us-cta'].contentText }}</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- cta End -->

templates/sections/map.html.twig
    <section class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d255282.32335424496!2d36.84739685!3d-1.3032089500000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f1172d84d49a7%3A0xf7cf0254b297924c!2sNairobi!5e0!3m2!1sen!2ske!4v1711958169667!5m2!1sen!2ske" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </section>

templates/sections/page_slider_0.html.twig
    <!--Main Slider-->
    <section class="main-slider subbanner mb-0" style="background-image:url(/site/images/uzima-well-being-hub-banner.jpg)">
         <div class="overlay"></div>
         <div class="po-t text-center">
            <div class="container">
                <h1>{{page.heading}}</h1>
                <p>{{page.metaDescription}}</p>
            </div>
        </div>
    </section>
    <!-- End Main Slider -->

templates/sections/qualities90.html.twig
    <!-- Start Min List Section -->
    <section class="slide-bottom pb-90 pt-90">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="min-s one-bg wow slideInRight" data-wow-delay="0ms" data-wow-duration="1200ms">
                        <span><img src="/site/images/delivery-truck.png" alt="" /></span>
                        <h3>{{ content['group-service-1-title'].contentText|nl2br }}</h3>
                        <p>{{ content['group-service-1-content'].contentText|nl2br }}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="min-s wow slideInUp" data-wow-delay="0ms" data-wow-duration="1400ms">
                        <span><img src="/site/images/w2.png" alt="" /></span>
                        <h3>{{ content['group-service-2-title'].contentText|nl2br }} </h3>
                        <p>{{ content['group-service-2-content'].contentText|nl2br }}</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="min-s one-bg wow slideInLeft" data-wow-delay="0ms" data-wow-duration="1200ms">
                        <span><img src="/site/images/teams.png" alt="" /></span>
                        <h3>{{ content['group-service-3-title'].contentText|nl2br }}</h3>
                        <p>{{ content['group-service-3-content'].contentText|nl2br }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Min List Section -->

templates/sections/service_banner.html.twig
	<!--Main Slider-->
    <section class="main-slider subbanner mb-90" style="background-image:url({{asset('site/images/page_images/' ~ page.featuredImage ) }})">
         <div class="overlay"></div>
         <div class="po-t text-center">
            <div class="container">
                <h1>{{page.heading}}</h1>
                <p>{{page.metaDescription}}</p>
            </div>
        </div>
    </section>
    <!-- End Main Slider -->

templates/sections/slider.html.twig
    <!--Main Slider-->
    <section class="main-slider subbanner mb-90" style="background-image:url({{asset('site/web_images/' ~ images['slider-image-1'].src ) }})">
         <div class="overlay"></div>
         <div class="po-t text-center">
            <div class="container">
                <h1>{{page.heading}}</h1>
                <p style="margin-bottom:50px;">{{page.metaDescription}}</p>
                <a href="{{ path( 'app_page', { 'page': 'our-services' } ) }}" class="theme-btn btn-style-orange" style="margin-right:0!important;float:none!important;">
                    {{ content['slider-button-cta'].contentText}}
                </a>

            </div>
        </div>
    </section>
    <!-- End Main Slider -->

    {# <!--Main Slider-->
    <section class="main-slider">

        <div class="rev_slider_wrapper fullwidthbanner-container" id="rev_slider_one_wrapper" data-source="gallery">
            <div class="rev_slider fullwidthabanner" id="rev_slider_one" data-version="5.4.1">
                <ul>

                    <li data-transition="slidingoverlayhorizontal" data-description="Slide Description" data-index="rs-1688" data-slotamount="default" data-thumb="{{asset('site/web_images/' ~ images['slider-image-1'].src ) }}" data-title="Slide Title">
                        <img alt="" class="rev-slidebg" data-bgfit="cover" data-bgparallax="10" data-bgposition="center center" data-bgrepeat="no-repeat" data-no-retina="" src="{{asset('site/web_images/' ~ images['slider-image-1'].src ) }}">
                        <div class="tp-caption"
                             data-paddingbottom="[0,0,0,0]"
                             data-paddingleft="[0,0,0,0]"
                             data-paddingright="[0,0,0,0]"
                             data-paddingtop="[0,0,0,0]"
                             data-responsive_offset="on"
                             data-type="text"
                             data-height="none"
                             data-width="['700','900','768','450']"
                             data-whitespace="normal"
                             data-hoffset="['55','75','75','15']"
                             data-voffset="['-20','-98','-80','-80']"
                             data-x="['left','left','left','left']"
                             data-y="['middle','middle','middle','middle']"
                             data-textalign="['top','top','top','top']"
                             data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[150%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <div class="text"><h1 class="sm-h1">{{page.heading}}</h1></div>
                        </div>
                        <div class="tp-caption "
                             data-paddingbottom="[0,0,0,0]"
                             data-paddingleft="[0,0,0,0]"
                             data-paddingright="[0,0,0,0]"
                             data-paddingtop="[0,0,0,0]"
                             data-responsive_offset="on"
                             data-type="text"
                             data-height="none"
                             data-width="['700','900','768','450']"
                             data-whitespace="normal"
                             data-hoffset="['55','75','75','15']"
                             data-voffset="['70','-10','20','10']"
                             data-x="['left','left','left','left']"
                             data-y="['middle','middle','middle','middle']"
                             data-textalign="['top','top','top','top']"
                             data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;","mask":"x:[-100%];y:0;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <h2>
                                <span>
                                    {{ content['invite-1'].contentText}}
                                </span>
                            </h2>
                        </div>

                        <div class="tp-caption tp-resizeme"
                             data-paddingbottom="[0,0,0,0]"
                             data-paddingleft="[0,0,0,0]"
                             data-paddingright="[0,0,0,0]"
                             data-paddingtop="[0,0,0,0]"
                             data-responsive_offset="on"
                             data-type="text"
                             data-height="none"
                             data-whitespace="normal"
                             data-width="['650','900','768','450']"
                             data-hoffset="['55','75','75','15']"
                             data-voffset="['170','110','110','90']"
                             data-x="['left','left','left','left']"
                             data-y="['middle','middle','middle','middle']"
                             data-textalign="['top','top','top','top']"
                             data-frames='[{"delay":1500,"speed":1500,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'>
                            <!-- Link Box -->
                            <div class="link-box">
                                <a href="{{ path( 'app_page', { 'page': 'our-services' } ) }}" class="theme-btn btn-style-orange">
                                    {{ content['slider-button-cta'].contentText}}
                                </a>

                            </div>
                        </div>

                    </li>

                    <li data-transition="slidingoverlayhorizontal" data-description="Slide Description" data-index="rs-1689" data-slotamount="default" data-thumb="{{asset('site/web_images/' ~ images['slider-image-2'].src ) }}" data-title="Slide Title">
                        <img alt="" class="rev-slidebg" data-bgfit="cover" data-bgparallax="10" data-bgposition="center center" data-bgrepeat="no-repeat" data-no-retina="" src="{{asset('site/web_images/' ~ images['slider-image-2'].src ) }}">
                        <div class="tp-caption"
                             data-paddingbottom="[0,0,0,0]"
                             data-paddingleft="[0,0,0,0]"
                             data-paddingright="[0,0,0,0]"
                             data-paddingtop="[0,0,0,0]"
                             data-responsive_offset="on"
                             data-type="text"
                             data-height="none"
                             data-width="['700','900','768','450']"
                             data-whitespace="normal"
                             data-hoffset="['55','75','75','15']"
                             data-voffset="['-20','-98','-80','-80']"
                             data-x="['left','left','left','left']"
                             data-y="['middle','middle','middle','middle']"
                             data-textalign="['top','top','top','top']"
                             data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[150%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <div class="text"><h3 class="sm-h1">{{page.metaTitle}}</h3></div>
                        </div>
                        <div class="tp-caption "
                             data-paddingbottom="[0,0,0,0]"
                             data-paddingleft="[0,0,0,0]"
                             data-paddingright="[0,0,0,0]"
                             data-paddingtop="[0,0,0,0]"
                             data-responsive_offset="on"
                             data-type="text"
                             data-height="none"
                             data-width="['700','900','768','450']"
                             data-whitespace="normal"
                             data-hoffset="['55','75','75','15']"
                             data-voffset="['70','-10','20','10']"
                             data-x="['left','left','left','left']"
                             data-y="['middle','middle','middle','middle']"
                             data-textalign="['top','top','top','top']"
                             data-frames='[{"delay":500,"speed":1500,"frame":"0","from":"x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;","mask":"x:[-100%];y:0;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeOut"},{"delay":"wait","speed":300,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                            <h2>
                                <span>
                                    {{ content['invite-2'].contentText}}
                                </span>
                            </h2>
                        </div>

                        <div class="tp-caption tp-resizeme"
                             data-paddingbottom="[0,0,0,0]"
                             data-paddingleft="[0,0,0,0]"
                             data-paddingright="[0,0,0,0]"
                             data-paddingtop="[0,0,0,0]"
                             data-responsive_offset="on"
                             data-type="text"
                             data-height="none"
                             data-whitespace="normal"
                             data-width="['650','900','768','450']"
                             data-hoffset="['55','75','75','15']"
                             data-voffset="['170','110','110','90']"
                             data-x="['left','left','left','left']"
                             data-y="['middle','middle','middle','middle']"
                             data-textalign="['top','top','top','top']"
                             data-frames='[{"delay":1500,"speed":1500,"frame":"0","from":"y:50px;opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]'>
                            <!-- Link Box -->
                            <div class="link-box">
                                <a href="{{ path( 'app_page', { 'page': 'our-services' } ) }}" class="theme-btn btn-style-orange">
                                    {{ content['slider-button-cta'].contentText}}
                                </a>

                            </div>
                        </div>

                    </li>

                </ul>
            </div>
        </div>
    </section>
    <!-- End Main Slider --> #}

templates/sections/variable_banner.html.twig
    <!--Main Slider-->
    <section class="main-slider subbanner mb-90" style="background-image:url(/site/images/uzima-well-being-hub-banner.jpg)">
         <div class="overlay"></div>
         <div class="po-t text-center">
            <div class="container">
                <h1>{{page.heading}}</h1>
                <p>{{page.metaDescription}}</p>
            </div>
        </div>
    </section>
    <!-- End Main Slider -->